services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - source: ${PWD}/.volumes/postgresql
        target: /var/lib/postgresql
        type: bind
        bind:
          create_host_path: true
    ports:
      - "${DB_PORT}:5432"

  cognito:
    image: jagregory/cognito-local:latest
    volumes:
      - source: ${PWD}/.volumes/cognito
        target: /app/.cognito
        type: bind
        bind:
          create_host_path: true
    ports:
      - "${COGNITO_PORT}:9229"
    # add an empty user pool json if not already existing, then run the service
    entrypoint: >
      /bin/sh -c "
        [ ! -f /app/.cognito/db/${COGNITO_POOL_ID}.json ] &&
        echo '{}' > /app/.cognito/db/${COGNITO_POOL_ID}.json
        node /app/start.js;
      "

  dynamodb:
    image: amazon/dynamodb-local:latest
    command: ["-jar", "DynamoDBLocal.jar", "-dbPath", "/var/db", "-sharedDb"]
    volumes:
      - source: ${PWD}/.volumes/dynamodb
        target: /var/db
        type: bind
        bind:
          create_host_path: true
    ports:
      - "${DYNAMODB_PORT}:8000"
    user: root

  bod:
    image: postgis/postgis:13-3.4
    environment:
      - POSTGRES_USER=${BOD_USER}
      - POSTGRES_PASSWORD=${BOD_PW}
      - POSTGRES_DB=${BOD_NAME}
    volumes:
      - source: ${PWD}/.volumes/postgis
        target: /var/lib/postgresql
        type: bind
        bind:
          create_host_path: true
    ports:
      - "${BOD_PORT}:5432"
