services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PW}
      - POSTGRES_DB=${DB_USER}
      - POSTGRES_DATABASE=${DB_NAME}
    volumes:
      - source: ${PWD}/.volumes/postgresql
        target: /var/lib/postgresql
        type: bind
        bind:
          create_host_path: true
    ports:
      - "${DB_PORT}:5432"

  bod:
    image: postgis/postgis:13-3.4
    environment:
      - POSTGRES_USER=${DB_BOD_NAME}
      - POSTGRES_PASSWORD=${DB_BOD_PW}
      - POSTGRES_DB=${DB_BOD_USER}
      - POSTGRES_DATABASE=${DB_BOD_NAME}
    volumes:
      - source: ${PWD}/.volumes/postgis
        target: /var/lib/postgresql
        type: bind
        bind:
          create_host_path: true
    ports:
      - "${DB_BOD_PORT}:5432"

  # db:
  #   image: postgis/postgis:16-3.4
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: dj_control

  #     PGDATA: /var/lib/postgresql/data/pgdata
  #     # POSTGRES_MULTIPLE_EXTENSIONS: postgis,postgis_topology
  #     # EXTRA_CONF: log_min_messages = ${DB_LOG_LEVEL:-FATAL}
  #   user: ${UID}
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - type: bind
  #       source: ${PWD}/pg-data
  #       target: /var/lib/postgresql/data
