# Generated by Django 5.0.9 on 2024-10-10 15:21

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0006_alter_provider_acronym_it_alter_provider_acronym_rm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                ('first_name', models.CharField(verbose_name='First name')),
                ('last_name', models.CharField(verbose_name='Last name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                (
                    'provider',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='provider.provider'
                    )
                ),
            ],
        ),
    ]
