# Generated by Django 5.0.9 on 2024-10-16 14:15

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0006_alter_provider_acronym_it_alter_provider_acronym_rm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'username',
                    models.CharField(primary_key=True, serialize=False, verbose_name='User name')
                ),
                ('first_name', models.CharField(verbose_name='First name')),
                ('last_name', models.CharField(verbose_name='Last name')),
                ('email', models.CharField(verbose_name='Email')),
                (
                    'provider',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='provider.provider'
                    )
                ),
            ],
        ),
    ]
