# Generated by Django 5.0.9 on 2025-02-12 14:58

import utils.fields

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0003_user_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=utils.fields.CustomSlugField(
                max_length=100, unique=True, verbose_name="User name"
            ),
        ),
    ]
