# Generated by Django 5.2.3 on 2025-07-03 14:20

import utils.fields

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_user_created_user_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'action_id',
                    utils.fields.CustomSlugField(
                        db_index=True, max_length=100, unique=True, verbose_name='External ID'
                    )
                ),
                ('name', models.CharField(verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'role_id',
                    utils.fields.CustomSlugField(
                        db_index=True, max_length=100, unique=True, verbose_name='External ID'
                    )
                ),
                ('name', models.CharField(verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'resource_type_id',
                    utils.fields.CustomSlugField(
                        db_index=True, max_length=100, unique=True, verbose_name='External ID'
                    )
                ),
                ('name', models.CharField(verbose_name='Name')),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='children',
                        to='access.resourcetype'
                    )
                ),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to='access.role'),
        ),
        migrations.CreateModel(
            name='RoleAccess',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    )
                ),
                (
                    'actions',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(), default=list, size=None
                    )
                ),
                (
                    'resource_type',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='access.resourcetype'
                    )
                ),
                (
                    'role',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='access.role'
                    )
                ),
            ],
        ),
    ]
