# Generated by Django 5.2.3 on 2025-07-03 14:21

from typing import Tuple

import access.models

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


def get_action_choices() -> Tuple[()]:
    return ()


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_action_role_resourcetype_user_roles_roleaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleaccess',
            name='actions',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(choices=get_action_choices), default=list, size=None
            ),
        ),
    ]
