# Generated by Django 5.2.3 on 2025-07-10 14:53

import django.contrib.postgres.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_alter_roleaccess_actions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcetype',
            name='parent',
        ),
        migrations.AddField(
            model_name='roleaccess',
            name='policy_id',
            field=models.CharField(blank=True, null=True, verbose_name='Policy ID'),
        ),
        migrations.AlterField(
            model_name='roleaccess',
            name='actions',
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(), default=list, size=None
            ),
        ),
    ]
