# Generated by Django 5.0.9 on 2024-09-16 11:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "provider",
            "0004_alter_provider_acronym_de_alter_provider_acronym_en_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="provider",
            options={},
        ),
    ]
