# Generated by Django 5.0.9 on 2024-09-18 15:09

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0005_alter_provider_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='acronym_it',
            field=models.CharField(blank=True, null=True, verbose_name='Acronym (Italian)'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='acronym_rm',
            field=models.CharField(blank=True, null=True, verbose_name='Acronym (Romansh)'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name_it',
            field=models.CharField(blank=True, null=True, verbose_name='Name (Italian)'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='name_rm',
            field=models.CharField(blank=True, null=True, verbose_name='Name (Romansh)'),
        ),
    ]
