# Generated by Django 5.0.9 on 2024-10-01 14:26

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        (
            "provider",
            "0006_alter_provider_acronym_it_alter_provider_acronym_rm_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="_legacy_id",
            field=models.IntegerField(
                blank=True,
                help_text="This field is used to track objects imported from the BOD",
                null=True,
                verbose_name="Legacy ID",
            ),
        ),
    ]
