# Generated by Django 5.0.9 on 2025-01-30 12:56

from utils.short_id import generate_short_id

from django.apps.registry import Apps
from django.db import migrations
from django.db import models
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def populate_external_id(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Provider = apps.get_model('provider', 'Provider')
    for obj in Provider.objects.all():
        obj.external_id = generate_short_id()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0007_provider__legacy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='external_id',
            field=models.CharField(
                default=generate_short_id,
                null=True,
                help_text=
                "This is the externally visible ID, usually of format 'ch.<acronym>'. In BOD this was tracked in column 'attribution'",
                verbose_name='External ID'
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_external_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='provider',
            name='external_id',
            field=models.CharField(
                default=generate_short_id,
                db_index=True,
                unique=True,
                verbose_name='External ID',
                help_text=
                "This is the externally visible ID, usually of format 'ch.<acronym>'. In BOD this was tracked in column 'attribution'",
            ),
        ),
    ]
