# Generated by Django 5.0.9 on 2025-02-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0008_provider_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='slug',
            new_name='provider_id',
        ),
    ]
