# Generated by Django 5.0.12 on 2025-02-18 09:57

import utils.fields

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0008_provider_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provider',
            old_name='slug',
            new_name='provider_id',
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_id',
            field=utils.fields.CustomSlugField(
                db_index=True, max_length=100, unique=True, verbose_name='External ID'
            ),
        ),
    ]
