# Generated by Django 5.0.9 on 2024-11-27 08:27

import utils.fields

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("distributions", "0006_alter_dataset_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="PackageDistribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    utils.fields.CustomSlugField(max_length=100, verbose_name="Slug"),
                ),
                (
                    "managed_by_stac",
                    models.BooleanField(max_length=100, verbose_name="Managed by STAC"),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="distributions.dataset",
                    ),
                ),
            ],
        ),
    ]
