# Generated by Django 5.0.9 on 2025-02-03 09:28

import utils.fields
from utils.short_id import generate_short_id

from django.apps.registry import Apps
from django.db import migrations
from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def populate_slug(apps: Apps, schema_editor: BaseDatabaseSchemaEditor) -> None:
    Attribution = apps.get_model("distributions", "Attribution")
    for obj in Attribution.objects.all():
        obj.slug = generate_short_id()
        obj.save()


class Migration(migrations.Migration):
    dependencies = [
        ("distributions", "0007_packagedistribution"),
    ]

    operations = [
        migrations.AddField(
            model_name="attribution",
            name="slug",
            field=utils.fields.CustomSlugField(
                default="1", max_length=100, verbose_name="Slug"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(populate_slug, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="attribution",
            name="slug",
            field=utils.fields.CustomSlugField(
                db_index=True,
                unique=True,
                max_length=100,
                verbose_name="Slug",
            ),
        ),
    ]
