# Generated by Django 5.0.9 on 2025-02-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0009_alter_dataset_slug_alter_packagedistribution_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribution',
            old_name='slug',
            new_name='attribution_id',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='slug',
            new_name='dataset_id',
        ),
        migrations.RenameField(
            model_name='packagedistribution',
            old_name='slug',
            new_name='package_distribution_id',
        ),
    ]
