# Generated by Django 5.0.14 on 2025-04-09 07:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0010_rename_slug_attribution_attribution_id_and_more_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagedistribution',
            name='_legacy_imported',
            field=models.BooleanField(
                default=False,
                help_text='This field is used to track objects imported from STAC',
                verbose_name='Legacy Imported'
            ),
        ),
        migrations.AlterField(
            model_name='packagedistribution',
            name='managed_by_stac',
            field=models.BooleanField(verbose_name='Managed by STAC'),
        ),
    ]
