# Generated by Django 5.2.14 on 2026-05-18 11:51

import django.contrib.postgres.fields
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='BodContactOrganisation',
            fields=[
                ('pk_contactorganisation_id', models.AutoField(primary_key=True, serialize=False)),
                ('abkuerzung_de', models.CharField(blank=True, max_length=255, null=True)),
                ('abkuerzung_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('abkuerzung_en', models.CharField(blank=True, max_length=255, null=True)),
                ('abkuerzung_it', models.CharField(blank=True, max_length=255, null=True)),
                ('abkuerzung_rm', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(blank=True, max_length=255, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_it', models.CharField(blank=True, max_length=255, null=True)),
                ('name_rm', models.CharField(blank=True, max_length=255, null=True)),
                ('attribution', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'contactorganisation',
                'managed': settings.TESTING,
            },
        ),
        migrations.CreateModel(
            name='BodDataset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('id_dataset', models.TextField()),
                ('fk_geocat', models.TextField()),
                ('fk_contactorganisation_id', models.IntegerField(blank=True, null=True)),
                ('staging', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dataset',
                'managed': settings.TESTING,
            },
        ),
        migrations.CreateModel(
            name='BodGeocatPublish',
            fields=[
                ('bgdi_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('fk_id_dataset', models.TextField()),
                ('bezeichnung_de', models.CharField(blank=True, max_length=5000, null=True)),
                ('bezeichnung_fr', models.CharField(blank=True, max_length=5000, null=True)),
                ('bezeichnung_it', models.CharField(blank=True, max_length=5000, null=True)),
                ('bezeichnung_rm', models.CharField(blank=True, max_length=5000, null=True)),
                ('bezeichnung_en', models.CharField(blank=True, max_length=5000, null=True)),
                ('abstract_de', models.CharField(blank=True, max_length=5000, null=True)),
                ('abstract_fr', models.CharField(blank=True, max_length=5000, null=True)),
                ('abstract_it', models.CharField(blank=True, max_length=5000, null=True)),
                ('abstract_rm', models.CharField(blank=True, max_length=5000, null=True)),
                ('abstract_en', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'geocat_publish',
                'managed': settings.TESTING,
            },
        ),
        migrations.CreateModel(
            name='BodLayersJS',
            fields=[
                ('bgdi_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('layer_id', models.CharField(blank=True, max_length=5000, null=True)),
                ('bod_layer_id', models.CharField(blank=True, max_length=5000, null=True)),
                ('topics', models.CharField(blank=True, max_length=5000, null=True)),
                ('chargeable', models.BooleanField()),
                ('staging', models.CharField(blank=True, max_length=5000, null=True)),
                ('server_layername', models.CharField(blank=True, max_length=5000, null=True)),
                ('attribution', models.CharField(blank=True, max_length=5000, null=True)),
                ('layertype', models.CharField(blank=True, max_length=5000, null=True)),
                ('opacity', models.FloatField(blank=True, null=True)),
                ('minresolution', models.FloatField(blank=True, null=True)),
                ('maxresolution', models.FloatField(blank=True, null=True)),
                (
                    'extent',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.FloatField(blank=True, null=True), blank=True, size=None
                    )
                ),
                ('backgroundlayer', models.BooleanField()),
                ('tooltip', models.BooleanField()),
                ('searchable', models.BooleanField()),
                ('timeenabled', models.BooleanField()),
                ('haslegend', models.BooleanField()),
                ('singletile', models.BooleanField()),
                ('highlightable', models.BooleanField()),
                ('wms_layers', models.CharField(blank=True, max_length=5000, null=True)),
                ('time_behaviour', models.CharField(blank=True, max_length=5000, null=True)),
                ('image_format', models.CharField(blank=True, max_length=5000, null=True)),
                ('tilematrix_resolution_max', models.FloatField(blank=True, null=True)),
                (
                    'timestamps',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=5000, null=True),
                        size=None
                    )
                ),
                ('parentlayerid', models.CharField(blank=True, max_length=5000, null=True)),
                (
                    'sublayersids',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=5000, null=True),
                        size=None
                    )
                ),
                ('time_get_parameter', models.CharField(blank=True, max_length=5000, null=True)),
                ('time_format', models.CharField(blank=True, max_length=5000, null=True)),
                ('wms_gutter', models.IntegerField(blank=True, null=True)),
                ('sphinx_index', models.CharField(blank=True, max_length=5000, null=True)),
                ('geojson_url_de', models.CharField(blank=True, max_length=5000, null=True)),
                ('geojson_url_fr', models.CharField(blank=True, max_length=5000, null=True)),
                ('geojson_url_it', models.CharField(blank=True, max_length=5000, null=True)),
                ('geojson_url_en', models.CharField(blank=True, max_length=5000, null=True)),
                ('geojson_url_rm', models.CharField(blank=True, max_length=5000, null=True)),
                ('geojson_update_delay', models.IntegerField(blank=True, null=True)),
                (
                    'shop_option_arr',
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(blank=True, max_length=5000, null=True),
                        size=None
                    )
                ),
                ('srid', models.CharField(blank=True, max_length=5000, null=True)),
                ('fk_config3d', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'view_layers_js',
                'managed': settings.TESTING,
            },
        ),
        migrations.CreateModel(
            name='BodTranslations',
            fields=[
                ('msg_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('de', models.CharField(blank=True, max_length=5000, null=True)),
                ('fr', models.CharField(blank=True, max_length=5000, null=True)),
                ('it', models.CharField(blank=True, max_length=5000, null=True)),
                ('rm', models.CharField(blank=True, max_length=5000, null=True)),
                ('en', models.CharField(blank=True, max_length=5000, null=True)),
            ],
            options={
                'db_table': 'translations',
                'managed': settings.TESTING,
            },
        ),
    ]
