# Generated by Django 5.0.9 on 2024-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='ContactOrganisation',
            fields=[
                ('pk_contactorganisation_id', models.AutoField(primary_key=True, serialize=False)),
                ('abkuerzung_de', models.CharField(blank=True, max_length=255, null=True)),
                ('abkuerzung_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('abkuerzung_en', models.CharField(blank=True, max_length=255, null=True)),
                ('abkuerzung_it', models.CharField(blank=True, max_length=255, null=True)),
                ('abkuerzung_rm', models.CharField(blank=True, max_length=255, null=True)),
                ('name_de', models.CharField(blank=True, max_length=255, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_it', models.CharField(blank=True, max_length=255, null=True)),
                ('name_rm', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'contactorganisation',
            },
        ),
    ]
