# Generated by Django 5.0.14 on 2025-04-09 13:21

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('bod', '0002_bodgeocatpublish'),
    ]

    operations = [
        migrations.AddField(
            model_name='boddataset',
            name='fk_geocat',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
